sudo: false
language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
- "./node_modules/bower/bin/bower install"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
notifications:
  webhooks:
    urls:
      secure: RaVEv4a1Dk75pN5R+0/gfdZleNvw++ojCkwxS1Nrm6hCWLAdfRpDL5QPq/a6iKYu6+HFEt5b37YUIx14Q12L7BhVBtLQhbxEwRV0gD00CcfuxqHENv52vNIVXH0MkENFwW0hE9HaMVXkFho0IvHmSBYNXSQywyP6LhL3fP+Ia+Y=
    on_success: change
    on_failure: always
env:
  global:
  - secure: BE8kRmR7tK6Akxru7zEdXs6W6vQnJYWluBtKi3DUJx29CQ6lzD8OvnBLOl2MaVeeXK63xDxhKQC8OQZ8Ux5Y78WYnWpKtA+r/GZuhkMQCIx7z+xpnBlWZCGjxK0USrlnuZL1sBA1AI7lB3burXuxivAfj++j1WdcX2jBl91204U=
  - secure: TCgiYb5FeyuXq2bmCguavSMZuAUhz2oZZPIIY+ksIPxEZY6eoIRvMDOZeJnUknNnDzX/XhXXFGSgSZ6fKflNH4xEeQeonxRWczh0sF5p8i8tv+ZUs4PECBuy4phRBISfJ4mtF5ai42t1x4EBgv506Zo9Ea6I/akAj9H7+d7b1bw=
